### ISSUE TITLE
Outras corpora do português

### ISSUE THREAD

**Issue by jcsilva** [fabiocmazzo/corpusportugues#1]
Oi,

muito interessante seu projeto! Como trabalho com algumas coisas relacionadas, sei de algumas outras fontes de texto do português do Brasil que podem ser úteis:

1. http://www.laps.ufpa.br/falabrasil/files/CorporaTextos1.5.rar
2. http://www.laps.ufpa.br/falabrasil/files/LapsFolha1.0.rar

Os dois links foram retirados de: http://www.laps.ufpa.br/falabrasil/downloads.php

Talvez valha a pena juntar esse material ao seu corpus. Só é importante verificar se dígitos, datas, valores monetários etc estão normalizados da mesma forma. Caso não estejam, talvez fique melhor mantê-los separados.

Outra sugestão seria remover as linhas em branco de seu arquivo. Ele já está bem grande e há muitas linhas sem nenhum conteúdo.

Até,
Eduardo

**Comment by fabiocmazzo** [comment]
Opa, Show de bola Eduardo, vou adicionar o material ao meu Corpus, obrigado pela ajuda. Vou também limpar as linhas em branco como sugerido :D

**Comment by fabiocmazzo** [comment]
Issue corrigido na versão 1.0.1:

1. Limpeza das  linhas em branco;
2. Inclusão dos corpus citados.

Obrigado pela contribuição!
