### ISSUE TITLE
Metadados

### ISSUE THREAD

**Issue by verissimomanoel** [fabiocmazzo/corpusportugues#2]
@fabiocmazzo esse corpus que você disponibilizou já está com os metadados?

**Comment by fabiocmazzo** [comment]
Olá Verissimo, 

  Não, nesse caso são apenas os modelos utilizados pelo MITIE, se puder explique melhor como pretende utilizar e quais ferramentas irá utilizar que talvez possa ajudá-lo.

Abraços,

**Comment by verissimomanoel** [comment]
Prezado Fábio,
No seu dataset você coloca um tópico: Mais do que artigos, dizendo que é possível ter um dump do wikipedia com as discussões.
O que eu quero é exatamente isso, ou seja, além do texto do artigo quero também as discussões para ter o corpus em uma linguagem mais informal.
Você sabe como fazer isso?

**Comment by fabiocmazzo** [comment]
Entendi, o Dump do Wikipedia contém os metadados e discussões, você pode alterar a ferramenta https://github.com/rspeer/wiki2text para gerar o texto limpo com as discussões antes de treinar o modelo.

**Comment by verissimomanoel** [comment]
@fabiocmazzo não achei o dump com as discussões. No dump que eu baixei só vem o texto mesmo, tentei pegar por exemplo o Inri Cristo que você citou mas não encontrei aqueles textos dentro do XML do dump.
